#
# Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apex-oracle-deployments-gui
{{- include "oracle-db-labels" . |indent 2}}
spec:
  replicas: {{ default 1 .Values.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 100
      maxUnavailable: 100
    type: RollingUpdate
  selector:
    matchLabels:
      heritage: {{ template "fullname" . }}
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        heritage: {{ template "fullname" . }}
        app: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 30
    {{- if .Values.imagePullSecrets}}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
    {{- end }}
      securityContext:
        runAsUser: 54321
        fsGroup: 54321
    {{- if or .Values.availabilityDomain .Values.nodeLabels}}
      nodeSelector:
      {{- range $key, $value := .Values.nodeLabels }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- if .Values.availabilityDomain }}
        failure-domain.beta.kubernetes.io/zone: "{{ .Values.availabilityDomain }}"
      {{- end }}
    {{- end }}
      containers:
        - name: oracle-db
          image: {{ .Values.image }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.imagePullPolicy | quote }}
          ports:
            - containerPort: 1521
            - containerPort: 5500
            - containerPort: 8023
            - containerPort: 8080
            - containerPort: 9043
          {{- if .Values.persistence }}
          volumeMounts:
            - mountPath: /opt/oracle/oradata
              name: datamount
          {{- end }}
{{- include "oracle-db-env" . | indent 10 }}
      {{- if .Values.persistence }}
      volumes:
        - name: datamount
          persistentVolumeClaim:
            claimName: {{ template "fullname" . }}
      {{- end }}

